# Generated by Django 3.1.1 on 2020-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512)),
                ('file_size', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('file_size', 'file_name')},
            },
        ),
    ]
