# Generated by Django 3.1.1 on 2020-09-14 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512)),
                ('file_size', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('file_size', 'file_name')},
            },
        ),
        migrations.CreateModel(
            name='FileToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('key_word_coefficient', models.FloatField(null=True)),
                ('count', models.PositiveSmallIntegerField(null=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab_1.filemodel')),
            ],
        ),
    ]
